apiVersion: apps/v1
kind: Deployment
metadata:
  name: velocity-proxy
  namespace: velocity
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: velocity-proxy
  template:
    metadata:
      labels:
        app: velocity-proxy
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 10001
        runAsGroup: 10001
      containers:
        - name: proxy
          image: ghcr.io/ahabscheid/velocity:0.1.0
          imagePullPolicy: IfNotPresent
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: false
            capabilities:
              drop: ["ALL"]
          args:
            - proxy
            - --target
            - ws://upstream.default.svc.cluster.local:4000
            - --host
            - 0.0.0.0
            - --port
            - "4100"
            - --listener-engine
            - ws
