export type Direction = "agent->server" | "server->agent";

export interface ProxyOptions {
  target: string;
  targetPool?: {
    targets: string[];
    ewmaAlpha: number;
    ejectFailures: number;
    ejectMs: number;
    probeIntervalMs: number;
    probeTimeoutMs: number;
    initialLatencyMs: number;
    connectionPenaltyMs: number;
    failurePenaltyMs: number;
    unhealthyPenaltyMs: number;
  };
  listenHost: string;
  listenPort: number;
  listenerEngine?: "ws" | "uwebsockets";
  listenerMaxPayloadBytes?: number;
  ingressH2H3Pilot: boolean;
  batchWindowMs: number;
  batchMaxMessages: number;
  batchMaxBytes: number;
  minBatchWindowMs: number;
  maxBatchWindowMs: number;
  latencyBudgetMs: number;
  enableZstd: boolean;
  zstdMinBytes: number;
  zstdMinGainRatio: number;
  enableZstdDictionary: boolean;
  zstdDictionaryBase64?: string;
  zstdDictionaryMinBytes: number;
  enableProtobuf: boolean;
  enableDelta: boolean;
  structuredDeltaTypes: string[];
  autoFallback: boolean;
  enableNegotiation: boolean;
  negotiationTimeoutMs: number;
  enablePassthroughMerge: boolean;
  safeMode: boolean;
  breakerThreshold: number;
  breakerWindowMs: number;
  breakerCooldownMs: number;
  rollbackBreachThreshold: number;
  rollbackWindowMs: number;
  maxInboundQueue: number;
  maxOutstandingBatches: number;
  maxSocketBackpressureBytes: number;
  heartbeatIntervalMs?: number;
  heartbeatTimeoutMs?: number;
  upstreamHandshakeTimeoutMs?: number;
  upstreamMaxPayloadBytes?: number;
  upstreamPerMessageDeflate?: boolean;
  logFormat: "text" | "json";
  otlpHttpEndpoint?: string;
  otlpIntervalMs: number;
  otlpServiceName: string;
  metricsHost?: string;
  metricsPort?: number;
  canary?: {
    percent: number;
    promotionWindowMs: number;
    minSessions: number;
    stateFile?: string;
  };
  policy?: {
    opaEndpoint: string;
    opaPath: string;
    timeoutMs: number;
    failOpen: boolean;
  };
  rateLimit?: {
    controlPlaneEndpoint: string;
    timeoutMs: number;
    failOpen: boolean;
  };
  authn?: {
    required: boolean;
    jwksUrl: string;
